# Generated by Django 5.2.12 on 2026-04-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('study_id', models.CharField(max_length=200)),
                ('instance_ids', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_opened', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
